<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>83085d08-f188-4dde-8125-845adcfad994</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IceboxKitchen.Contracts\IceboxKitchen.Contracts.csproj" />
    <ProjectReference Include="..\IceboxKitchen.Application\IceboxKitchen.Application.csproj" />
    <ProjectReference Include="..\IceboxKitchen.Infrastructure\IceboxKitchen.Infrastructure.csproj" />
  </ItemGroup>

</Project>
