@host=https://localhost:7201
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDMwZTNiNy01N2JlLTRjNTctODJjZC1lMWY4MzZlZmRmM2UiLCJnaXZlbl9uYW1lIjoiTHVpeiIsImZhbWlseV9uYW1lIjoiV2FrYW5vIiwianRpIjoiMjIwYWZlZjItOTAyYS00YjE0LTlhOTUtZTUxYTdkOTRiMmIzIiwiZXhwIjoxNzg2OTk0MzIyLCJpc3MiOiJJY2Vib3hLaXRjaGVuIiwiYXVkIjoiSWNlYm94S2l0Y2hlbiJ9.aXF37WCZeCI7Qa0Kd4EbelbWJ9DmQKBQCZEQcXe8F-g